### ISSUE TITLE
UDP socket support?

### ISSUE THREAD

**Issue by justmark** [Zewo/Venice#13]
I noticed that your readme doesn't have UDP socket support checked off.  Is this something you're planning on adding?  Definitely interested in utilizing this project, but UDP is a requirement for us.

Thanks!

**Comment by paulofaria** [comment]
Hello, 

I'm on a trip right now, but I can add UDP sockets support next week. (:

**Comment by justmark** [comment]
Thats great news... why the sad face?  ;)

Enjoy your trip.

**Comment by paulofaria** [comment]
I'll keep the issue open as a reminder. ☺

**Comment by justmark** [comment]
Hi,

Checking in to see if you've had a chance to look at this yet.

Thanks

**Comment by paulofaria** [comment]
This is coming in the big refactor I'm working on. If everything goes well I'll release it this weekend.

**Comment by paulofaria** [comment]
just so you know. I started working on `UDP`, but I didn't have time to test it yet. We're working on a big refactor. So things still lack organisation. The current implementation is here:

https://github.com/Zewo/Flux/blob/master/Sources/Flux/UDP/UDP.swift

You can fork `Venice`, add that file and test it. When the refactor is finished, UDP won't be merged with Venice. Actually, tcp sockets, and ip, will be removed from Venice and will be moved separate repos that depend on `CLibvenice` instead of `Venice`. `Flux` as well will be deleted once the refactor is finished. Don't rely on it. If you find any bugs or have some other trouble let me know.  (:

**Comment by justmark** [comment]
Thanks - very much appreciated!
